### ISSUE TITLE
Doesn't seem to work with Python 3

### ISSUE THREAD

**Issue by yucongo** [RonenNess/grepfunc#1]
Hello. I was looking for something similar to grep and came across to your project.

Unfortunately, it doesnt seem to work with Python 3.

When I tried 

    from grepfunc import grep

I got:

    In [56]: from grepfunc import grep
    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    <ipython-input-56-5f3ea5e5b70f> in <module>()
    ----> 1 from grepfunc import grep

    c:\python\python36\lib\site-packages\grepfunc\__init__.py in <module>()
          8 __license__ = 'MIT'
          9
    ---> 10 from grepfunc import (grep, grep_iter)
         11

    ImportError: cannot import name 'grep'

**Comment by RonenNess** [comment]
Fixed the import issue + tests, will release a new package sometime soon... Meanwhile you can fetch the source from master branch.

Thanks :)

**Comment by RonenNess** [comment]
@yucongo Hi man just letting you know I uploaded a new version to pip, it should be working now in Python 3.

Cheers.
